<?php
declare(strict_types=1);

// Commonroom SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CommonroomUtility::setRegistrar(function (CommonroomUtility $u): void {
    $u->clean = [CommonroomClean::class, 'call'];
    $u->done = [CommonroomDone::class, 'call'];
    $u->make_error = [CommonroomMakeError::class, 'call'];
    $u->feature_add = [CommonroomFeatureAdd::class, 'call'];
    $u->feature_hook = [CommonroomFeatureHook::class, 'call'];
    $u->feature_init = [CommonroomFeatureInit::class, 'call'];
    $u->fetcher = [CommonroomFetcher::class, 'call'];
    $u->make_fetch_def = [CommonroomMakeFetchDef::class, 'call'];
    $u->make_context = [CommonroomMakeContext::class, 'call'];
    $u->make_options = [CommonroomMakeOptions::class, 'call'];
    $u->make_request = [CommonroomMakeRequest::class, 'call'];
    $u->make_response = [CommonroomMakeResponse::class, 'call'];
    $u->make_result = [CommonroomMakeResult::class, 'call'];
    $u->make_point = [CommonroomMakePoint::class, 'call'];
    $u->make_spec = [CommonroomMakeSpec::class, 'call'];
    $u->make_url = [CommonroomMakeUrl::class, 'call'];
    $u->param = [CommonroomParam::class, 'call'];
    $u->prepare_auth = [CommonroomPrepareAuth::class, 'call'];
    $u->prepare_body = [CommonroomPrepareBody::class, 'call'];
    $u->prepare_headers = [CommonroomPrepareHeaders::class, 'call'];
    $u->prepare_method = [CommonroomPrepareMethod::class, 'call'];
    $u->prepare_params = [CommonroomPrepareParams::class, 'call'];
    $u->prepare_path = [CommonroomPreparePath::class, 'call'];
    $u->prepare_query = [CommonroomPrepareQuery::class, 'call'];
    $u->graphql_body = [CommonroomGraphql::class, 'body'];
    $u->graphql_errors = [CommonroomGraphql::class, 'errors'];
    $u->result_basic = [CommonroomResultBasic::class, 'call'];
    $u->result_body = [CommonroomResultBody::class, 'call'];
    $u->result_headers = [CommonroomResultHeaders::class, 'call'];
    $u->transform_request = [CommonroomTransformRequest::class, 'call'];
    $u->transform_response = [CommonroomTransformResponse::class, 'call'];
});
